# Generated by Django 3.2.8 on 2021-12-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
  
        migrations.CreateModel(
            name='OrganDonate',
            fields=[
                ('patient_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=5)),
                ('contact_num', models.CharField(blank=True, max_length=11, null=True)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('need_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'organ_donate',
                'managed': False,
            },
        ),
    ]
