# Generated by Django 3.2.8 on 2021-12-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicine_id', models.CharField(db_column='Medicine Id', max_length=15, primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(db_column='Medicine Name', max_length=20)),
                ('patient_id', models.CharField(max_length=10)),
                ('expired_date', models.DateTimeField(db_column='Expired Date')),
                ('price', models.SmallIntegerField(db_column='Price')),
            ],
            options={
                'db_table': 'medicine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('nurse_id', models.CharField(db_column='Nurse_ID', max_length=6, primary_key=True, serialize=False)),
                ('nurse_name', models.CharField(db_column='Nurse_Name', max_length=15)),
                ('floor_no', models.IntegerField(db_column='Floor_No')),
                ('bed_no', models.CharField(db_column='Bed_No', max_length=30)),
            ],
            options={
                'db_table': 'nurse',
                'managed': False,
            },
        ),
    ]