# Generated by Django 3.2.8 on 2021-12-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_user1'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('blood_group', models.CharField(max_length=3)),
                ('age', models.CharField(max_length=3)),
                ('email', models.CharField(max_length=30)),
                ('user_type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
